<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Forms\Login\" />
    <Folder Include="Forms\Home\" />
    <Folder Include="Forms\Attraction\" />
    <Folder Include="Forms\Itinerary\" />
  </ItemGroup>

</Project>