// <auto-generated />
using System;
using ItineraryPlannerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItineraryPlannerApp.Migrations
{
    [DbContext(typeof(ItineraryDbContext))]
    [Migration("20260815024846_CheckSliderSync")]
    partial class CheckSliderSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ItineraryPlannerApp.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttractionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Labels")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.AttractionLabel", b =>
                {
                    b.Property<int>("AttractionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttractionId", "Category");

                    b.ToTable("AttractionLabel");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArriveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalEntryPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Itineraries", (string)null);
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("ItineraryBlock");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromStation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToStation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransportBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("route")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("TransportBlockId");

                    b.ToTable("TransportNotes", (string)null);
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.TransitAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttractionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttractionId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinuteWalk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("AttractionId1");

                    b.ToTable("TransitAccess");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportBlock", b =>
                {
                    b.HasBaseType("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("INTEGER");

                    b.ToTable("TransportBlocks", (string)null);
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.VisitBlock", b =>
                {
                    b.HasBaseType("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock");

                    b.Property<int>("AttractionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("AttractionId");

                    b.ToTable("VisitBlocks", (string)null);
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Attraction", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItineraryPlannerApp.Models.Location", "Location", b1 =>
                        {
                            b1.Property<int>("AttractionId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.Navigation("City");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.AttractionLabel", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.City", b =>
                {
                    b.OwnsOne("ItineraryPlannerApp.Models.MapSlider", "Slider", b1 =>
                        {
                            b1.Property<int>("CityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("Slider")
                        .IsRequired();
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.Itinerary", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Itinerary.Itinerary", "Itinerary")
                        .WithMany("ItineraryBlocks")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportNote", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Itinerary.TransportBlock", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryPlannerApp.Models.Itinerary.TransportBlock", null)
                        .WithMany("Notes")
                        .HasForeignKey("TransportBlockId");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.TransitAccess", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryPlannerApp.Models.Attraction", null)
                        .WithMany("CloseStations")
                        .HasForeignKey("AttractionId1");

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportBlock", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock", null)
                        .WithOne()
                        .HasForeignKey("ItineraryPlannerApp.Models.Itinerary.TransportBlock", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.VisitBlock", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock", null)
                        .WithOne()
                        .HasForeignKey("ItineraryPlannerApp.Models.Itinerary.VisitBlock", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Attraction", b =>
                {
                    b.Navigation("CloseStations");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.Itinerary", b =>
                {
                    b.Navigation("ItineraryBlocks");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportBlock", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
