// <auto-generated />
using System;
using ItineraryPlannerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItineraryPlannerApp.Migrations
{
    [DbContext(typeof(ItineraryDbContext))]
    partial class ItineraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ItineraryPlannerApp.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttractionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Labels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LocationId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArriveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalEntryPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("ItineraryBlocks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ItineraryBlock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromStation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToStation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("TransportNotes");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.TransitAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttractionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinuteWalk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.ToTable("TransitAccess");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportBlock", b =>
                {
                    b.HasBaseType("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TransportBlock");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.VisitBlock", b =>
                {
                    b.HasBaseType("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock");

                    b.Property<int>("AttractionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("AttractionId");

                    b.HasDiscriminator().HasValue("VisitBlock");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Attraction", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryPlannerApp.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.Itinerary", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.ItineraryBlock", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Itinerary.Itinerary", "Itinerary")
                        .WithMany("ItineraryBlocks")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportNote", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Itinerary.TransportBlock", "Block")
                        .WithMany("Notes")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.TransitAccess", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Attraction", "Attraction")
                        .WithMany("CloseStations")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.VisitBlock", b =>
                {
                    b.HasOne("ItineraryPlannerApp.Models.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Attraction", b =>
                {
                    b.Navigation("CloseStations");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.City", b =>
                {
                    b.Navigation("Attractions");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.Itinerary", b =>
                {
                    b.Navigation("ItineraryBlocks");
                });

            modelBuilder.Entity("ItineraryPlannerApp.Models.Itinerary.TransportBlock", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
